# Generated by Django 3.2.6 on 2021-08-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PfreeEateries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eatery_types', models.CharField(choices=[('KF', 'Koreanfood'), ('SN', 'Snack'), ('CH', 'Chicken'), ('PI', 'Pizza'), ('CF', 'Chinesefood'), ('FF', 'Fastfood'), ('BO', 'Bossam'), ('HS', 'Hotsoup')], default='KOREANFOOD', max_length=2)),
                ('eatery', models.CharField(max_length=50)),
                ('echolv', models.CharField(max_length=10)),
                ('perf', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
