# Generated by Django 3.2.6 on 2021-08-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfreers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfreeeateries',
            name='echof_co_cnt',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
